version: "3.8"
services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mlplatformdb
      POSTGRES_USER: mluser
      POSTGRES_PASSWORD: mlpassword
    ports:
      - "5432:5432"

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      sh -c "pip install --no-cache-dir psycopg2-binary && \
      mlflow server \
        --backend-store-uri postgresql://mluser:mlpassword@postgres/mlplatformdb \
        --default-artifact-root s3://ml-platform \
        --host 0.0.0.0 --port 5000"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    ports:
      - "5001:5000"
