name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Flake8 (lint)
        run: |
          pip install flake8
          flake8 app.py

      - name: Install kubectl
        run: |
          curl -sSLO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Validate Kubernetes manifests
        run: kubectl apply --dry-run=client -f k8s/

      - name: Build Docker image (CI test)
        run: docker build -t highpeaks-ml-platform-ci:build .
